// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { UpdateUserUserPostData, UpdateUserUserPostResponse, UpdateUserUserPostError, GetUserByUsernameUserGetUserByUsernamePostData, GetUserByUsernameUserGetUserByUsernamePostResponse, GetUserByUsernameUserGetUserByUsernamePostError, HealthCheckHealthGetData } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Update User
 */
export const updateUserUserPost = <ThrowOnError extends boolean = false>(options: Options<UpdateUserUserPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UpdateUserUserPostResponse, UpdateUserUserPostError, ThrowOnError>({
        url: '/user/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get User By Username
 */
export const getUserByUsernameUserGetUserByUsernamePost = <ThrowOnError extends boolean = false>(options: Options<GetUserByUsernameUserGetUserByUsernamePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetUserByUsernameUserGetUserByUsernamePostResponse, GetUserByUsernameUserGetUserByUsernamePostError, ThrowOnError>({
        url: '/user/get_user_by_username',
        ...options
    });
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};