// This file is auto-generated by @hey-api/openapi-ts

export type CreateTeamRequest = {
    team_name: string;
};

export type DagAction = 'create' | 'add_edge' | 'delete_edge';

export type DagRequest = {
    dag_id?: string | null;
    first_task_id: string;
    second_task_id?: string;
    team_id: string;
    action: DagAction;
};

export type DagResponse = {
    success: boolean;
    message: string;
    dag_id?: string | null;
    new_dag_id?: string | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type SearchResponse = {
    reply: string;
    weeks: Array<Week>;
    total_count: number;
};

export type SearchType = 'regular' | 'semantic' | 'compare';

export type TaskFocus = 'low' | 'medium' | 'high';

export type TaskPriority = 'low' | 'medium' | 'high' | 'emergency';

export type TaskRequest = {
    task_id?: string | null;
    task_name?: string | null;
    team_id?: string | null;
    deadline?: string | null;
    points?: number | null;
    priority?: TaskPriority | null;
    focus?: TaskFocus | null;
    description?: string | null;
    notes?: string | null;
    action: TaskAction;
};

export type UpdateUserOption = 'create' | 'update' | 'delete';

export type UpdateUserRequest = {
    user_id: string;
    team_id?: string | null;
    action: UpdateUserOption;
};

export type UserTasksRequest = {
    user_id: string;
    task_id: string;
    action: Option;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type WeekRequestType = 'search_query' | 'compare_weeks' | 'get_weeks';

export type WeekResponse = {
    weeks: Array<Week>;
    total_count: number;
};

export type Dag = {
    dag_id?: string | null;
    team_id: string;
    dag_graph: {
        [key: string]: Array<string>;
    };
};

export type Option = 'add' | 'delete';

/**
 * A task represents a unit of work assigned to a team.
 *
 * Tasks are the fundamental building blocks of project management, containing information about
 * what needs to be done, when it needs to be done, and how important it is. Each task belongs
 * to a team and can be worked on by team members.
 */
export type Task = {
    id?: string | null;
    task_name: string;
    team_id: string;
    priority?: TaskPriority;
    focus?: TaskFocus;
    deadline?: string | null;
    points?: number | null;
    date_of_completion?: string | null;
    date_of_creation?: string;
    description?: string | null;
    notes?: string | null;
};

export type TaskAction = 'create' | 'edit' | 'delete' | 'complete';

/**
 * A team represents a group of users working together on tasks.
 *
 * Teams are the organizational units that contain users and tasks. Each team has a unique name
 * and can have multiple users as members. Teams provide the context for task collaboration
 * and project management.
 */
export type Team = {
    team_name: string;
    id: string;
};

/**
 * A user represents a team member in the system.
 *
 * Users are the individual participants who work on tasks within teams. Each user must belong
 * to exactly one team, and can collaborate on tasks within that team. Users are identified
 * by their unique username and UUID.
 */
export type User = {
    username: string;
    team_id: string;
    id: string;
};

export type UserTasks = {
    user_id: string;
    task_id: string;
    assigned_at?: string | null;
};

/**
 * A model representing a weekly summary of a user's productivity and accomplishments.
 *
 * This model captures a week's worth of work activity, including tasks completed,
 * collaboration metrics, and AI-generated feedback to improve productivity.
 * Each week spans from start_date to end_date (7 days later).
 */
export type Week = {
    id?: string | null;
    /**
     * The start date of the week
     */
    start_date: string;
    /**
     * The end date of the week (7 days after start_date)
     */
    end_date: string;
    /**
     * The ID of the user whose productivity is being summarized
     */
    user_id: string;
    /**
     * AI-generated summary of the week's work and productivity patterns
     */
    summary?: string | null;
    /**
     * AI-generated feedback aimed at improving worker productivity
     */
    feedback?: string | null;
    /**
     * List of user IDs who were assigned roles on tasks during this week
     */
    collaborators?: Array<string> | null;
    /**
     * List of task IDs where deadlines were missed during this week
     */
    missed_deadlines?: Array<string> | null;
    /**
     * List of task IDs that were completed during this week
     */
    completed_tasks?: Array<string> | null;
    /**
     * Total points completed, where points represent estimated hours of work
     */
    points_completed?: number | null;
};

export type UpdateUserUserPostData = {
    body: UpdateUserRequest;
    path?: never;
    query?: never;
    url: '/user/';
};

export type UpdateUserUserPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserUserPostError = UpdateUserUserPostErrors[keyof UpdateUserUserPostErrors];

export type UpdateUserUserPostResponses = {
    /**
     * Successful Response
     */
    201: User;
};

export type UpdateUserUserPostResponse = UpdateUserUserPostResponses[keyof UpdateUserUserPostResponses];

export type GetUserByUsernameUserGetUserByUsernameGetData = {
    body?: never;
    path?: never;
    query: {
        username: string;
    };
    url: '/user/get_user_by_username';
};

export type GetUserByUsernameUserGetUserByUsernameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByUsernameUserGetUserByUsernameGetError = GetUserByUsernameUserGetUserByUsernameGetErrors[keyof GetUserByUsernameUserGetUserByUsernameGetErrors];

export type GetUserByUsernameUserGetUserByUsernameGetResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetUserByUsernameUserGetUserByUsernameGetResponse = GetUserByUsernameUserGetUserByUsernameGetResponses[keyof GetUserByUsernameUserGetUserByUsernameGetResponses];

export type GetUsersByTeamUserByTeamGetData = {
    body?: never;
    path?: never;
    query: {
        team_id: string;
    };
    url: '/user/by_team';
};

export type GetUsersByTeamUserByTeamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersByTeamUserByTeamGetError = GetUsersByTeamUserByTeamGetErrors[keyof GetUsersByTeamUserByTeamGetErrors];

export type GetUsersByTeamUserByTeamGetResponses = {
    /**
     * Successful Response
     */
    200: Array<User>;
};

export type GetUsersByTeamUserByTeamGetResponse = GetUsersByTeamUserByTeamGetResponses[keyof GetUsersByTeamUserByTeamGetResponses];

export type GetAllTasksTasksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/';
};

export type GetAllTasksTasksGetResponses = {
    /**
     * Successful Response
     */
    200: Array<Task>;
};

export type GetAllTasksTasksGetResponse = GetAllTasksTasksGetResponses[keyof GetAllTasksTasksGetResponses];

export type TaskPostTasksPostData = {
    body: TaskRequest;
    path?: never;
    query?: never;
    url: '/tasks/';
};

export type TaskPostTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TaskPostTasksPostError = TaskPostTasksPostErrors[keyof TaskPostTasksPostErrors];

export type TaskPostTasksPostResponses = {
    /**
     * Successful Response
     */
    201: Task;
};

export type TaskPostTasksPostResponse = TaskPostTasksPostResponses[keyof TaskPostTasksPostResponses];

export type GetAllTeamsTeamsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/teams/';
};

export type GetAllTeamsTeamsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<Team>;
};

export type GetAllTeamsTeamsGetResponse = GetAllTeamsTeamsGetResponses[keyof GetAllTeamsTeamsGetResponses];

export type CreateTeamTeamsPostData = {
    body: CreateTeamRequest;
    path?: never;
    query?: never;
    url: '/teams/';
};

export type CreateTeamTeamsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTeamTeamsPostError = CreateTeamTeamsPostErrors[keyof CreateTeamTeamsPostErrors];

export type CreateTeamTeamsPostResponses = {
    /**
     * Successful Response
     */
    201: Team;
};

export type CreateTeamTeamsPostResponse = CreateTeamTeamsPostResponses[keyof CreateTeamTeamsPostResponses];

export type DeleteTeamTeamsTeamIdDeleteData = {
    body?: never;
    path: {
        team_id: string;
    };
    query?: never;
    url: '/teams/{team_id}';
};

export type DeleteTeamTeamsTeamIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTeamTeamsTeamIdDeleteError = DeleteTeamTeamsTeamIdDeleteErrors[keyof DeleteTeamTeamsTeamIdDeleteErrors];

export type DeleteTeamTeamsTeamIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTeamTeamsTeamIdDeleteResponse = DeleteTeamTeamsTeamIdDeleteResponses[keyof DeleteTeamTeamsTeamIdDeleteResponses];

export type GetAllDagsDagGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dag/';
};

export type GetAllDagsDagGetResponses = {
    /**
     * Successful Response
     */
    200: Array<Dag>;
};

export type GetAllDagsDagGetResponse = GetAllDagsDagGetResponses[keyof GetAllDagsDagGetResponses];

export type DagActionDagPostData = {
    body: DagRequest;
    path?: never;
    query?: never;
    url: '/dag/';
};

export type DagActionDagPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DagActionDagPostError = DagActionDagPostErrors[keyof DagActionDagPostErrors];

export type DagActionDagPostResponses = {
    /**
     * Successful Response
     */
    200: DagResponse;
};

export type DagActionDagPostResponse = DagActionDagPostResponses[keyof DagActionDagPostResponses];

export type GetAllUserTasksUserTasksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user_tasks/';
};

export type GetAllUserTasksUserTasksGetResponses = {
    /**
     * Successful Response
     */
    200: Array<UserTasks>;
};

export type GetAllUserTasksUserTasksGetResponse = GetAllUserTasksUserTasksGetResponses[keyof GetAllUserTasksUserTasksGetResponses];

export type ModifyUserTaskUserTasksPostData = {
    body: UserTasksRequest;
    path?: never;
    query?: never;
    url: '/user_tasks/';
};

export type ModifyUserTaskUserTasksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModifyUserTaskUserTasksPostError = ModifyUserTaskUserTasksPostErrors[keyof ModifyUserTaskUserTasksPostErrors];

export type ModifyUserTaskUserTasksPostResponses = {
    /**
     * Successful Response
     */
    201: UserTasks;
};

export type ModifyUserTaskUserTasksPostResponse = ModifyUserTaskUserTasksPostResponses[keyof ModifyUserTaskUserTasksPostResponses];

export type GetWeeksWeekGetData = {
    body?: never;
    path?: never;
    query: {
        request_type: WeekRequestType;
        query?: string | null;
        week_id?: string | null;
        number_of_weeks: number;
        start_date?: string | null;
        end_date?: string | null;
        user_id?: string | null;
        team_id?: string | null;
        collaborators?: Array<string> | null;
        missed_deadlines_range?: [
            number,
            number
        ] | null;
        completed_task_range?: [
            number,
            number
        ] | null;
        points_range?: [
            number,
            number
        ] | null;
    };
    url: '/week/';
};

export type GetWeeksWeekGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWeeksWeekGetError = GetWeeksWeekGetErrors[keyof GetWeeksWeekGetErrors];

export type GetWeeksWeekGetResponses = {
    /**
     * Successful Response
     */
    200: WeekResponse;
};

export type GetWeeksWeekGetResponse = GetWeeksWeekGetResponses[keyof GetWeeksWeekGetResponses];

export type AgenticSearchAgenticSearchGetData = {
    body?: never;
    path?: never;
    query: {
        search_type: SearchType;
        query?: string | null;
        week_id?: string | null;
        number_of_weeks?: number;
        start_date?: string | null;
        end_date?: string | null;
        user_id?: string | null;
        team_id?: string | null;
        collaborators?: Array<string> | null;
        missed_deadlines_range?: [
            number,
            number
        ] | null;
        completed_task_range?: [
            number,
            number
        ] | null;
        points_range?: [
            number,
            number
        ] | null;
    };
    url: '/agentic/search';
};

export type AgenticSearchAgenticSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgenticSearchAgenticSearchGetError = AgenticSearchAgenticSearchGetErrors[keyof AgenticSearchAgenticSearchGetErrors];

export type AgenticSearchAgenticSearchGetResponses = {
    /**
     * Successful Response
     */
    200: SearchResponse;
};

export type AgenticSearchAgenticSearchGetResponse = AgenticSearchAgenticSearchGetResponses[keyof AgenticSearchAgenticSearchGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};