version: '3.8'
services:
  db:
    image: ankane/pgvector:latest
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME:-postgres}
      POSTGRES_USER: ${POSTGRES_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Schema files (order matters)
      - ./db/schema/team.sql:/docker-entrypoint-initdb.d/01_team.sql:ro
      - ./db/schema/user.sql:/docker-entrypoint-initdb.d/02_user.sql:ro
      - ./db/schema/tasks.sql:/docker-entrypoint-initdb.d/04_tasks.sql:ro
      - ./db/schema/user_tasks.sql:/docker-entrypoint-initdb.d/05_user_tasks.sql:ro
      - ./db/schema/week.sql:/docker-entrypoint-initdb.d/06_week.sql:ro
      - ./db/schema/dag.sql:/docker-entrypoint-initdb.d/07_dag.sql:ro
      # Data files (order matters)
      - ./db/example_data/init_teams.sql:/docker-entrypoint-initdb.d/11_init_teams.sql:ro
      - ./db/example_data/init_users.sql:/docker-entrypoint-initdb.d/12_init_users.sql:ro
      - ./db/example_data/init_tasks.sql:/docker-entrypoint-initdb.d/14_init_tasks.sql:ro
      - ./db/example_data/init_user_tasks.sql:/docker-entrypoint-initdb.d/15_init_user_tasks.sql:ro
      - ./db/example_data/init_dag.sql:/docker-entrypoint-initdb.d/16_init_dag.sql:ro
      - ./db/example_data/init_week.sql:/docker-entrypoint-initdb.d/17_init_week.sql:ro

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: dagger_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./dagger_frontend
      dockerfile: Dockerfile
    container_name: dagger_frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
