version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME:-postgres}
      POSTGRES_USER: ${POSTGRES_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema/user.sql:/docker-entrypoint-initdb.d/01_user.sql:ro
      - ./db/example_data/init_users.sql:/docker-entrypoint-initdb.d/02_init_users.sql:ro
volumes:
  postgres_data:
