import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from './components/NavBar';
import ContextProviders from './components/ContextProviders';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-[#181A1B]`}>
        <ContextProviders>
          <div className="flex flex-col min-h-screen">
            <NavBar />
            <main className="flex-1 overflow-hidden pt-16">
              {children}
            </main>
          </div>
        </ContextProviders>
      </body>
    </html>
  );
}
