import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from './contexts/auth_context'
import { TeamProvider } from './contexts/team_context'
import NavBar from './components/NavBar'

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AuthProvider>
          <TeamProvider>
            <NavBar />
            {children}
          </TeamProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
